services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_password123"
    ports:
      - "${PORT_PREFIX}143:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: dbplayground
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${PORT_PREFIX}543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  rules:
    image: quay.io/kiegroup/kie-server-showcase:7.74.0.Final
    environment:
      KIE_SERVER_USER: kieserver
      KIE_SERVER_PWD: kieserver1!
    ports:
      - "62600:8080"

volumes:
  sqlserver-data:
  postgres-data: