package rules

global java.util.Map orderDecision;

import java.time.LocalDate;
import java.time.Period;
import java.util.Map;

rule "Allow adult customer"
when
    $order : Map(this["birthDate"] != null, this["evaluationAtUtc"] != null)
    eval(Period.between(LocalDate.parse($order.get("birthDate").toString()), LocalDate.parse($order.get("evaluationAtUtc").toString().substring(0, 10))).getYears() >= 18)
then
    orderDecision.put("allowed", true);
    orderDecision.put("reason", "Customer is at least 18 years old.");
end

rule "Deny non-adult customer"
when
    $order : Map(this["birthDate"] != null, this["evaluationAtUtc"] != null)
    eval(Period.between(LocalDate.parse($order.get("birthDate").toString()), LocalDate.parse($order.get("evaluationAtUtc").toString().substring(0, 10))).getYears() < 18)
then
    orderDecision.put("allowed", false);
    orderDecision.put("reason", "Customer must be at least 18 years old.");
end

rule "Deny invalid order fact"
when
    $order : Map()
    eval(!$order.containsKey("birthDate")
    || $order.get("birthDate") == null
        || !$order.containsKey("evaluationAtUtc")
    || $order.get("evaluationAtUtc") == null)
then
    orderDecision.put("allowed", false);
    orderDecision.put("reason", "The order fact is missing birthDate or evaluationAtUtc.");
end
